language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
services:
  - docker
env:
  - =y2khub/remotecache
before_script:
  - dotnet restore
script:  
  - dotnet publish -c Release -r linux-x64 --self-contained false -o out
  - docker build --rm -f Dockerfile -t y2khub/remotecache .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push y2khub/remotecache
deploy:
  provider: script
  script: 
  - echo $DEPLOY_KEY > deployment_key.txt && chmod 600 deployment_key.txt
  - ssh -i deployment_key.txt $DEPLOY_AUTHORITY "docker pull y2khub/remotecache"
  - ssh -i deployment_key.txt $DEPLOY_AUTHORITY "docker rm -f y2khub/remotecache"
  - ssh -i deployment_key.txt $DEPLOY_AUTHORITY "docker run -d -p 8080:80 -v $HOME/remote-cache/cache:/app/cache y2khub/remotecache"