//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemoteCacheApi.WorkerServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkerServices.IWorkerService")]
    public interface IWorkerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkerService/AddWork", ReplyAction="http://tempuri.org/IWorkerService/AddWorkResponse")]
        void AddWork(System.Uri source);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkerService/GetPathForImage", ReplyAction="http://tempuri.org/IWorkerService/GetPathForImageResponse")]
        string GetPathForImage(System.Uri url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkerServiceChannel : global::RemoteCacheApi.WorkerServices.IWorkerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkerServiceClient : System.ServiceModel.ClientBase<global::RemoteCacheApi.WorkerServices.IWorkerService>, global::RemoteCacheApi.WorkerServices.IWorkerService {
        
        public WorkerServiceClient() {
        }
        
        public WorkerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddWork(System.Uri source) {
            base.Channel.AddWork(source);
        }
        
        public string GetPathForImage(System.Uri url) {
            return base.Channel.GetPathForImage(url);
        }
    }
}
